#!/bin/bash
# ATTACH N DISKS TO THE N INSTANCES
# ===================================
source ./tasks/gce/config

set -e
echo "Attaching $NUM_DISK_PER_INSTANCE disks to the $N instances..."
for ((i=1; i<=$N; i++))
do  
    instance_id=${GLUSTER_INSTANCES[$i-1]}
    for ((di=1; di<=$NUM_DISK_PER_INSTANCE; di++))
    do
        disk=$(gcloud:disk_name $i $di)
        info "$instance_id" "Attaching disk $disk..."
        gcloud compute instances attach-disk --quiet $instance_id \
            --mode "rw" \
            --zone "$ZONE" \
            --disk "$disk"
    done
done  
