#!/bin/bash
# ATTACH N DISKS TO THE N INSTANCES
# ===================================
source ./tasks/gce/config

set -e
echo "Attaching $NUM_DISK_PER_INSTANCE disks to the $N instances..."
for ((i=1; i<=$N; i++))
do
    instance_id=${GLUSTER_INSTANCES[$i-1]}
    for ((di=1; di<=$NUM_DISK_PER_INSTANCE; di++))
    do
        disk_name=$(gcloud:disk_name $i $di)
        disk_num_users=$(gcloud compute disks describe $disk_name --format json | jq '.users | length')

        if [[ $disk_num_users == 0 ]] ; then
            info "$instance_id" "Attaching disk $disk_name..."
            gcloud compute instances attach-disk --quiet $instance_id \
                --mode "rw" \
                --zone "$ZONE" \
                --disk "$disk_name"
        else
            # will be attached like this /dev/disk/by-id/google-persistent-disk-1
            info "$instance_id" "Disk $disk_name is already attached."
        fi
    done
done
