#!/bin/bash
if [[ -z "$DEPLOYMENT_ID" ]] ; then
    echo "DEPLOYMENT_ID is not defined"
    exit 1
fi

echo Using DEPLOYMENT_ID=$DEPLOYMENT_ID
mkdir -p deployments/$DEPLOYMENT_ID

N=3
PREFIX=example

ZONEID=a
ZONE=asia-east1-$ZONEID

# WARNING: You have selected a disk size of under [200GB]. This may result in
# poor I/O performance. For more information, see:
# https://developers.google.com/compute/docs/disks#performance.
DISK_SIZE=200GB
DISK_TYPE=pd-standard
DISK_LABELS="service=glusterfs"
# DISK_TYPE=pd-ssd

INSTANCE_TAGS=glusterfs
MACHINE_TYPE=n1-standard-1
IMAGE_TYPE=centos-7-v20170620
IMAGE_PROJECT=centos-cloud
BOOTDISK_TYPE=pd-standard
BOOTDISK_SIZE=100GB

HEKETI_JWT_USER_SECRET=secretk3y
HEKETI_JWT_ADMIN_SECRET=secretk3y
HEKETI_KEY_DIR=/etc/heketi

if [[ ! -e "./deployments/$DEPLOYMENT_ID/config" ]] ; then
    echo "./deployments/$DEPLOYMENT_ID/config does not exist"
    exit 1
fi

echo "Found ./deployments/$DEPLOYMENT_ID/config"
source ./deployments/$DEPLOYMENT_ID/config



declare -a GLUSTER_INSTANCES=()
for ((i=1; i<=$N; i++))
do
  GLUSTER_INSTANCES+=("$PREFIX-gluster-$ZONEID-$i")
done


HEKETI_INSTANCE=${GLUSTER_INSTANCES[0]}

declare -a probes
probes=(${GLUSTER_INSTANCES[@]})
# shift is only for zsh
# shift probes
probes=(${probes[@]:1})

TIMESTAMP=$(date "+%s")

source functions.sh
