#!/bin/bash
N=3
PREFIX=example

ZONEID=a
ZONE=asia-east1-$ZONEID

# WARNING: You have selected a disk size of under [200GB]. This may result in
# poor I/O performance. For more information, see:
# https://developers.google.com/compute/docs/disks#performance.
DISK_SIZE=200GB
DISK_TYPE=pd-standard
DISK_LABELS="service=glusterfs"
# DISK_TYPE=pd-ssd

INSTANCE_TAGS=glusterfs
MACHINE_TYPE=n1-standard-1
IMAGE_TYPE=centos-7-v20170620
IMAGE_PROJECT=centos-cloud
BOOTDISK_TYPE=pd-standard
BOOTDISK_SIZE=10

HEKETI_JWT_USER_SECRET=secretk3y
HEKETI_JWT_ADMIN_SECRET=secretk3y
HEKETI_KEY_DIR=/etc/heketi

if [[ -e ./config ]] ; then
    source ./config
fi

declare -a gluster_instances=()
for ((i=1; i<=$N; i++))
do
  gluster_instances+=("$PREFIX-gluster-$i")
done
declare -a probes
heketi_instance=${gluster_instances[0]}
probes=(${gluster_instances[@]})
# shift is only for zsh
# shift probes
probes=(${probes[@]:1})
