#!/bin/bash
# CREATE N DISKS
# ===================================
source ./tasks/gce/config
set -e
echo "Creating $N disks..."

declare -a pids=()
for ((i=1; i<=$N; i++))
do
    gcloud_create_disk "$PREFIX-gluster-$ZONEID-disk-$i" &
    pids+=($!)
done

echo "Waiting for all disks get ready..."
wait "${pids[@]}"
