#!/usr/bin/env bash
# CREATE N DISKS
# ===================================
source ./tasks/gce/config
set -e

declare -A diskMap=()
for disk_name in $(gcloud compute disks list --filter="zone:($ZONE)" | awk 'NR > 1 { print $1 }')
do
    diskMap["$disk_name"]=1
done

echo "Preparing $NUM_DISK_PER_INSTANCE disks on $N instances..."
declare -a pids=()
for ((i=1; i<=$N; i++))
do
    for ((di=1; di<=$NUM_DISK_PER_INSTANCE; di++))
    do
        disk_name=$(gcloud:disk_name $i $di)
        if [[ "${diskMap[$disk_name]}" == "1" ]] ; then
            echo "Disk $disk_name already exists, skip"
        else
            echo "Creating disk $disk_name with size $DISK_SIZE"
            gcloud:create_disk "$disk_name" \
                --size $DISK_SIZE \
                --labels $DISK_LABELS \
                --type $DISK_TYPE \
                &
            pids+=($!)
        fi
    done
done

echo "Waiting for all disks get ready..."
wait "${pids[@]}"
