#!/bin/bash
# CREATE N DISKS
# ===================================
source ./tasks/gce/config
set -e
echo "Creating $N disks..."

declare -a pids=()
for ((i=1; i<=$N; i++))
do
    disk="$PREFIX-gluster-$ZONEID-disk-$i"
    gcloud compute disks create --quiet "$disk" \
        --size "$DISK_SIZE" \
        --zone "$ZONE" \
        --labels "$DISK_LABELS" \
        --type "$DISK_TYPE" &
    pids+=($!)
done
wait "${pids[@]}"
