#!/bin/bash
source ./tasks/gce/config
set -e

echo "===> Installing json-patch"
go get -x github.com/evanphx/json-patch/cmd/json-patch

heketi_json_file="deployments/$DEPLOYMENT_ID/heketi.json"

heketi_get_config_file "$HEKETI_INSTANCE" "$heketi_json_file"
heketi_patch_config_file "$heketi_json_file"
heketi_put_config_file "$HEKETI_INSTANCE" "$heketi_json_file"
heketi_selfcheck "$HEKETI_INSTANCE"
