#!/bin/bash
source ./tasks/gce/config
set -e

echo "===> Installing json-patch"
go get -x github.com/evanphx/json-patch/cmd/json-patch

# Setting up heketi.json
echo "Setting up heketi.json ..."
gcloud compute scp $heketi_instance:/etc/heketi/heketi.json deployments/$DEPLOYMENT_ID/heketi.json
cat <<PATCH > deployments/$DEPLOYMENT_ID/heketi.json.patch
[
    { "op": "replace", "path": "/glusterfs/sshexec/keyfile", "value": "$HEKETI_KEY_DIR/id_rsa" },
    { "op": "replace", "path": "/glusterfs/sshexec/user", "value": "root" },
    { "op": "replace", "path": "/glusterfs/sshexec/port", "value": "22" },
    { "op": "replace", "path": "/glusterfs/sshexec/fstab", "value": "/etc/fstab" },
    { "op": "replace", "path": "/glusterfs/executor", "value": "ssh" },
    { "op": "replace", "path": "/jwt/user/key", "value": "$HEKETI_JWT_USER_SECRET" },
    { "op": "replace", "path": "/jwt/admin/key", "value": "$HEKETI_JWT_ADMIN_SECRET" }
]
PATCH
mv deployments/$DEPLOYMENT_ID/heketi.json deployments/$DEPLOYMENT_ID/heketi.json.orig
cat deployments/$DEPLOYMENT_ID/heketi.json.orig \
    | json-patch -p deployments/$DEPLOYMENT_ID/heketi.json.patch \
    | json_pp > deployments/$DEPLOYMENT_ID/heketi.json

gcloud compute scp deployments/$DEPLOYMENT_ID/heketi.json $heketi_instance:./heketi.json
gcloud compute ssh $heketi_instance --command "sudo cp -v heketi.json $HEKETI_KEY_DIR/heketi.json \
    && sudo chown heketi: $HEKETI_KEY_DIR/heketi.json \
    && sudo systemctl enable heketi \
    && sudo systemctl restart heketi"
gcloud compute ssh $heketi_instance --command "curl -s $heketi_instance:8080/hello"
