#!/bin/bash
source ./tasks/gce/config
declare -a pids=()
for ((i=1; i<=$N; i++))
do  
    instance_id=${GLUSTER_INSTANCES[$i-1]}
    disk="$PREFIX-gluster-$ZONEID-disk-$i"
    echo "$instance_id: detach disk $disk"
    gcloud compute instances detach-disk $instance_id \
        --disk $disk \
        --zone $ZONE
    pids+=($!)
done
wait "${pids[@]}"
