#!/bin/bash
source ./tasks/gce/config
set -e
rm -rf deployments/$DEPLOYMENT_ID/cache
mkdir -p deployments/$DEPLOYMENT_ID/cache
for instance_id in "${GLUSTER_INSTANCES[@]}"
do
    info "$instance_id" "fetching instance info ..."
    gcloud_instance_info "$instance_id" > /dev/null
done
