#!/bin/bash
source ./tasks/gce/config

cat <<JSON > deployments/$DEPLOYMENT_ID/topology.json
{
    "clusters": [ { "nodes": [ ] } ]
}
JSON

for instance_id in "${gluster_instances[@]}"
do
    subnet_ip=$(cat cache/$instance_id.json | jq --raw-output '.networkInterfaces[0].networkIP')
    cat <<PATCH > deployments/$DEPLOYMENT_ID/topology.patch.json
    [
        {
            "op": "add",
            "path": "/clusters/0/nodes/-",
            "value": {
                "node": {
                    "zone": 1,
                    "hostnames": {
                        "manage": [ "$instance_id" ],
                        "storage": [ "$subnet_ip" ]
                    }
                },
                "devices": [ "/dev/sdb" ]
            }
        }
    ]
PATCH
    (cat deployments/$DEPLOYMENT_ID/topology.json \
        | json-patch -p deployments/$DEPLOYMENT_ID/topology.patch.json \
        | json_pp > deployments/$DEPLOYMENT_ID/topology.json.new \
            && mv deployments/$DEPLOYMENT_ID/topology.json{.new,})
done
cat deployments/$DEPLOYMENT_ID/topology.json
