#!/bin/bash
source ./tasks/gce/config

declare -a DEVICE_PATHS=()

for ((i=1 ; i <= $NUM_DISK_PER_INSTANCE ; i++))
do
    DEVICE_PATHS+=($(printf '"%s"' "/dev/disk/by-id/google-persistent-disk-$i"))
done



cat <<JSON > deployments/$DEPLOYMENT_ID/topology.json
{
    "clusters": [ { "nodes": [ ] } ]
}
JSON

for instance_id in "${GLUSTER_INSTANCES[@]}"
do
    subnet_ip=$(cat deployments/$DEPLOYMENT_ID/cache/$instance_id.json | jq --raw-output '.networkInterfaces[0].networkIP')
    cat <<PATCH > deployments/$DEPLOYMENT_ID/topology.patch.json
    [
        {
            "op": "add",
            "path": "/clusters/0/nodes/-",
            "value": {
                "node": {
                    "zone": 1,
                    "hostnames": {
                        "manage": ["$instance_id"],
                        "storage": ["$subnet_ip"]
                    }
                },
                "devices": [
                    $(perl -e '$s = shift @ARGV; print join($s, @ARGV);' "," "${DEVICE_PATHS[@]}")
                ]
            }
        }
    ]
PATCH
    (cat deployments/$DEPLOYMENT_ID/topology.json \
        | json-patch -p deployments/$DEPLOYMENT_ID/topology.patch.json \
        | json_pp > deployments/$DEPLOYMENT_ID/topology.json.new \
            && mv deployments/$DEPLOYMENT_ID/topology.json{.new,})
done
cat deployments/$DEPLOYMENT_ID/topology.json
