#!/bin/bash
source ./tasks/gce/config
set -e

LOCAL_SSHKEY_DIR=deployments/$DEPLOYMENT_ID/keys
REMOTE_SSHKEY_DIR=keys

echo "Setting up gluster node ssh connection ..."
gcloud compute ssh $HEKETI_INSTANCE --command "mkdir -p $REMOTE_SSHKEY_DIR \
    && (cd $REMOTE_SSHKEY_DIR && ssh-keygen -f id_rsa -t rsa -N '')"
gcloud compute ssh $HEKETI_INSTANCE --command "sudo mkdir -p $HEKETI_KEY_DIR \
        && sudo cp -v $REMOTE_SSHKEY_DIR/id_rsa* $HEKETI_KEY_DIR \
        && sudo chown -R heketi: $HEKETI_KEY_DIR/id_rsa* \
        && sudo chmod 600 $HEKETI_KEY_DIR/id_rsa*"

echo "===> Cleaning up $LOCAL_SSHKEY_DIR"
rm -rf $LOCAL_SSHKEY_DIR

echo "===> Downloading ssh keys from $HEKETI_INSTANCE..."
gcloud compute scp --recurse $HEKETI_INSTANCE:./$REMOTE_SSHKEY_DIR $LOCAL_SSHKEY_DIR

echo "===> Generated SSH keys:"
find $LOCAL_SSHKEY_DIR -type f

for instance_id in "${GLUSTER_INSTANCES[@]}"
do
    echo "$instance_id: Sending public key ..."
    gcloud compute scp $LOCAL_SSHKEY_DIR/id_rsa.pub $instance_id:id_rsa.pub

    echo "$instance_id: Setting authorized_keys ..."
    gcloud compute ssh $instance_id --command "sudo mkdir -p /root/.ssh && sudo chmod 700 /root/.ssh"
    gcloud compute ssh $instance_id --command "cat id_rsa.pub | sudo tee --append /root/.ssh/authorized_keys"
    gcloud compute ssh $instance_id --command "sudo chmod 600 /root/.ssh/authorized_keys"
done
