#!/bin/bash
source ./tasks/gce/config
set -e

echo "===> Installing json-patch"
go get github.com/evanphx/json-patch/cmd/json-patch

heketi_json_file="deployments/$DEPLOYMENT_ID/heketi.json"

heketi:get_config_file "$HEKETI_INSTANCE" "$heketi_json_file"
heketi:patch_config_file "$heketi_json_file"
heketi:put_config_file "$HEKETI_INSTANCE" "$heketi_json_file"
heketi:selfcheck "$HEKETI_INSTANCE"
