#!/bin/bash
source ./tasks/gce/config

function heketi:install_on()
{
    local instance_id=$1

    info "$instance_id: Installing heketi..."
    gcloud:ssh_command "$instance_id" "sudo yum -y --quiet install heketi heketi-client"
}

function gcloud:instance_add_tag()
{
    local instance_id=$1
    shift
    info "$instance_id" "Adding tags {$*}..."
    gcloud compute instances add-tags "$instance_id" --tags "$*" --zone "$ZONE"
}

heketi:install_on "$HEKETI_INSTANCE"
gcloud:instance_add_tag "$HEKETI_INSTANCE" "heketi"
