#!/bin/bash
source ./tasks/gce/config

gcloud_instance_info $HEKETI_INSTANCE

export HEKETI_IP=$(gcloud_instance_network_ip $HEKETI_INSTANCE)
export HEKETI_EXTERNAL_IP=$(gcloud_instance_external_ip $HEKETI_INSTANCE)
export HEKETI_CLI_SERVER=http://$HEKETI_IP:8080
export HEKETI_SSH_KEYFILE=/etc/heketi/id_rsa
export HEKETI_SSH_USER=root
export HEKETI_SSH_PORT=22
docker run -it --rm --entrypoint heketi-cli \
    --volume $PWD/deployments/$DEPLOYMENT_ID:/data heketi/heketi \
    --server $HEKETI_CLI_SERVER topology info
