#!/bin/bash
source ./tasks/gce/config

function heketi_install_on()
{
    local instance_id=$1

    info "$instance_id: Installing heketi..."
    gcloud_ssh_command "$instance_id" "sudo yum -y --quiet install heketi heketi-client"
}

function gcloud_instance_tag()
{
    local instance_id=$1
    shift
    info "$instance_id" "Adding tags {$*}..."
    gcloud compute instances add-tags "$instance_id" --tags "$*" --zone "$ZONE"
}

heketi_install_on "$HEKETI_INSTANCE"
gcloud_instance_tag "$HEKETI_INSTANCE" "heketi"
