#!/bin/bash
source ./tasks/gce/config
echo "$HEKETI_INSTANCE: Installing heketi..."
gcloud compute ssh $HEKETI_INSTANCE --command "sudo yum -y --quiet install heketi heketi-client"

echo "$HEKETI_INSTANCE: Adding heketi tag..."
gcloud compute instances add-tags $HEKETI_INSTANCE --tags heketi --zone $ZONE
