#!/bin/bash
source ./tasks/gce/config

# SETTING UP GLUSTER SERVICES
# =====================================
for instance_id in "${GLUSTER_INSTANCES[@]}"
do
    glusterfs_install_server_on "$instance_id"
done
