#!/bin/bash
source ./tasks/gce/config

# CONNECTING PEERS
# =====================================
echo "Connecting peers..."
for probe in "${probes[@]}"
do
    echo "$HEKETI_INSTANCE: peer probe $probe..."
    gcloud compute ssh $HEKETI_INSTANCE \
        --command "sudo gluster peer probe $probe"
done
gcloud compute ssh $HEKETI_INSTANCE --command "sudo gluster peer status" | grep State
echo "Peers setup completed."
