#!/bin/bash
source ./tasks/gce/config

declare -a pids=()
for instance_id in "${GLUSTER_INSTANCES[@]}" ; do
    echo "$instance_id: stopping instance"
    gcloud compute instances stop $instance_id &
    pids+=($!)
done
wait "${pids[@]}"

