#!/bin/bash
set -e
export DEPLOYMENT_ID=$1
# https://github.com/mike-trewartha/gce-gluster-heketi-gke
# https://github.com/heketi/heketi/wiki/Kubernetes-Integration

# setup the the firewall rules
./tasks/gce/create-firewall-rules

# prepare the instances
./tasks/gce/create-instances
./tasks/gce/instances-add-tags

# prepare the glusterfs disks
./tasks/gce/create-disks
./tasks/gce/attach-disks

./tasks/gce/install-glusterfsd
./tasks/gce/setup-glusterfs-peers

./tasks/gce/heketi-install
./tasks/gce/heketi-install-ssh-keys
./tasks/gce/heketi-configure
./tasks/gce/heketi-generate-topology
./tasks/gce/heketi-deploy-topology

./tasks/kubernetes/install-glusterfs-client
./tasks/kubernetes/deploy
