#!/bin/bash
set -e
# https://github.com/mike-trewartha/gce-gluster-heketi-gke
# https://github.com/heketi/heketi/wiki/Kubernetes-Integration
# create instance names
./tasks/gce/create-disks
./tasks/gce/create-instances
./tasks/gce/attach-disks
# source ./tasks/gce/instances-add-tags

./tasks/gce/create-firewall-rules
./tasks/gce/install-glusterfsd
./tasks/gce/setup-glusterfs-peers
./tasks/gce/install-heketi
./tasks/gce/install-ssh-keys
./tasks/gce/deploy-heketi
./tasks/gce/fetch-instances-info
./tasks/gce/generate-topology
./tasks/gce/deploy-topology
