#!/bin/bash
export DEPLOYMENT_ID=$1
# ./tasks/gce/delete-firewall-rules
./tasks/gce/uninstall-glusterfsd
./tasks/gce/detach-disks
./tasks/gce/stop-instances
./tasks/gce/delete-instances
./tasks/gce/delete-disks
