#!/bin/bash
source ./tasks/gce/config


declare -a kube_nodes=()
while read instance ; do
    kube_nodes+=($instance)
done < <(kubernetes_get_nodes)
info "kubernetes" "Found ${kube_nodes[@]}"

for instance in "${kube_nodes[@]}"
do
    glusterfs_install_client_on "$instance"
done
